import { useCallback, useEffect, useState } from 'react'
import { api, type Explanation, type Field, type Mission, type Plan, type WellState } from './api'
import { MissionScreen } from './screens/Mission'
import { PlanScreen } from './screens/Plan'
import { RaceScreen } from './screens/Race'
import { Intro, Outro } from './screens/Title'
import { TraceScreen } from './screens/Trace'
import { TwinScreen } from './screens/Twin'

const STAGES = ['intro', 'mission', 'trace', 'twin', 'race', 'plan', 'outro'] as const
type Stage = (typeof STAGES)[number]
const NAV: [Stage, string][] = [['mission', 'MISSION'], ['trace', 'ANALYZE'], ['twin', 'DIGITAL TWIN'], ['race', 'COUNTERFACTUALS'], ['plan', 'PLAN']]
const DEFAULT: Mission = { well_id: 'BGW-08', target_bbl: 1600, deadline_d: 90, steam_budget_t: 1000, energy_budget_kwh: 7000 }

export default function App() {
  const [stage, setStage] = useState<Stage>('intro')
  const [mission, setMission] = useState<Mission>(DEFAULT)
  const [well, setWell] = useState<WellState | null>(null)
  const [field, setField] = useState<Field | null>(null)
  const [plan, setPlan] = useState<Plan | null>(null)
  const [why, setWhy] = useState<Explanation | null>(null)
  const [busy, setBusy] = useState(false)
  const [err, setErr] = useState('')

  useEffect(() => {
    api.field().then(setField).catch((e) => setErr(String(e)))
  }, [])
  useEffect(() => {
    api.well(mission.well_id).then(setWell).catch((e) => setErr(String(e)))
  }, [mission.well_id])

  const run = async () => {
    setBusy(true)
    setErr('')
    setWhy(null)
    try {
      const p = await api.mission(mission)
      if (!p.feasible) throw new Error(p.message)
      setPlan(p)
      setStage('trace')
      api.explain(mission).then(setWhy).catch(() => {})
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e))
    } finally {
      setBusy(false)
    }
  }

  const go = useCallback((dir: 1 | -1) => {
    setStage((s) => {
      const i = STAGES.indexOf(s) + dir
      if (i < 0 || i >= STAGES.length) return s
      if (!plan && STAGES[i] !== 'intro' && STAGES[i] !== 'mission') return s
      return STAGES[i]
    })
  }, [plan])

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if ((e.target as HTMLElement).tagName === 'INPUT' || (e.target as HTMLElement).tagName === 'TEXTAREA') return
      if (e.key === 'ArrowRight' || e.key === 'PageDown') go(1)
      if (e.key === 'ArrowLeft' || e.key === 'PageUp') go(-1)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [go])

  if (stage === 'intro') return <Intro onNext={() => setStage('mission')} />
  if (stage === 'outro') return <Outro onBack={() => setStage('plan')} />

  const at = STAGES.indexOf(stage)
  return (
    <div className="app">
      <header className="topbar">
        <div className="brand">WELL<b>TWIN</b> · BAGHEWALA</div>
        <nav className="steps">
          {NAV.map(([s, label]) => (
            <button key={s} className={s === stage ? 'on' : STAGES.indexOf(s) < at ? 'done' : ''}
              disabled={!plan && s !== 'mission'} onClick={() => setStage(s)}>{label}</button>
          ))}
        </nav>
        <span className="tag" title="No public Baghewala dataset exists; history is generated by the physics model with unmodelled variability and noise.">
          SYNTHETIC HISTORY · CALIBRATED TO PUBLISHED BAGHEWALA DATA
        </span>
      </header>
      <main className="stage">
        {err && <div className="panel red mono" style={{ marginBottom: 16 }}>{err}</div>}
        {stage === 'mission' && <MissionScreen well={well} field={field} mission={mission} setMission={setMission} onRun={run} busy={busy} />}
        {stage === 'trace' && plan && <TraceScreen plan={plan} onNext={() => setStage('twin')} />}
        {stage === 'twin' && plan && <TwinScreen plan={plan} onNext={() => setStage('race')} />}
        {stage === 'race' && plan && <RaceScreen plan={plan} onNext={() => setStage('plan')} />}
        {stage === 'plan' && plan && <PlanScreen plan={plan} why={why} onNext={() => setStage('outro')} />}
      </main>
    </div>
  )
}
