import { useState } from 'react'
import { api, fmt, type Mission, type WorkOrder } from './api'
import { useAfter } from './auto'

const when = (t: number | null) => (t ? new Date(t * 1000).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : '—')

/** The printable operating order: what the field crew actually receives. */
export function WorkOrderDoc({ wo }: { wo: WorkOrder }) {
  const p = wo.plan
  const m = p.mission
  return (
    <div className="print-area paper">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid #111', paddingBottom: 10 }}>
        <div>
          <div style={{ fontSize: 11, letterSpacing: '0.12em' }}>WELLTWIN · BAGHEWALA FIELD · CSS + SRP OPERATING ORDER</div>
          <div style={{ fontSize: 24, fontWeight: 800, marginTop: 4 }}>{wo.number} · {wo.well_id} · CSS cycle #{wo.cycle}</div>
        </div>
        <div style={{ textAlign: 'right', fontSize: 12 }}>
          <div className={`stamp ${wo.status}`}>{wo.status.toUpperCase()}</div>
          <div style={{ marginTop: 6 }}>issued {when(wo.created)}</div>
        </div>
      </div>

      <div style={{ fontSize: 12, margin: '10px 0 14px' }}>
        Mission: ≥ {fmt(m.target_bbl)} bbl within {m.deadline_d} days of cycle start · steam ≤ {fmt(m.steam_budget_t)} t · SRP energy ≤ {fmt(m.energy_budget_kwh)} kWh
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 }}>
        <div>
          <h4>1 · Steam injection (CSS)</h4>
          <table className="doc"><tbody>
            <tr><td>Steam volume</td><td>{fmt(p.x.steam_t)} t CWE</td></tr>
            <tr><td>Wellhead injection pressure</td><td>{p.x.inj_p_bar} bar (limit 150)</td></tr>
            <tr><td>Steam temperature (sat.)</td><td>{p.t_steam} °C</td></tr>
            <tr><td>Injection duration</td><td>{p.inj_days} days</td></tr>
            <tr><td>Soak</td><td>{p.x.soak_d} days</td></tr>
            <tr><td>Put on production</td><td>day {Math.ceil(p.prod_start)}</td></tr>
            <tr><td>Re-steam trigger</td><td>day {p.resteam_day} (oil &lt; 10 bopd)</td></tr>
          </tbody></table>
        </div>
        <div>
          <h4>2 · Sucker-rod pump (VFD schedule)</h4>
          <table className="doc">
            <thead><tr><th>From day</th><th>SPM</th><th>VFD</th></tr></thead>
            <tbody>
              {p.spm_schedule.map((s) => <tr key={s.from_day}><td>{s.from_day}</td><td>{s.spm.toFixed(2)}</td><td>{s.vfd_hz} Hz</td></tr>)}
            </tbody>
          </table>
          <div style={{ fontSize: 11, marginTop: 4 }}>Stroke {p.x.stroke_m.toFixed(1)} m · do not exceed scheduled SPM: rods float above it as the well cools.</div>
        </div>
      </div>

      <h4 style={{ marginTop: 14 }}>3 · Expected outcome (twin forecast)</h4>
      <table className="doc"><tbody>
        <tr><td>Oil by day {m.deadline_d}</td><td>P50 {fmt(p.p50)} bbl · P10–P90 {fmt(p.p10)}–{fmt(p.p90)} bbl · target reached day {p.day_target}</td></tr>
        <tr><td>Steam-oil ratio · energy · CO₂</td><td>{p.sor} m³/m³ · {fmt(p.energy_kwh)} kWh · {fmt(p.co2_t, 1)} t</td></tr>
        <tr><td>Rod float</td><td>0 days forecast (typical constant-SPM practice: {p.baseline_float_days} days)</td></tr>
        <tr><td>Evidence</td><td>closest past cycles {p.evidence.map((e) => `#${e.cycle}`).join(', ')}</td></tr>
      </tbody></table>

      <h4 style={{ marginTop: 14 }}>4 · Hold points</h4>
      <ul style={{ fontSize: 12, margin: '4px 0 0 18px', padding: 0, lineHeight: 1.6 }}>
        <li>Stop injection and inform the engineer if wellhead pressure exceeds 150 bar.</li>
        <li>If dyno minimum load approaches zero, reduce SPM one step and report. WellTwin Live Ops will also alert.</li>
        <li>Record daily oil, SPM and dyno cards; they are ingested after the cycle to recalibrate the twin.</li>
      </ul>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, marginTop: 18 }}>
        <div className="sign"><div>Prepared by (production engineer)</div><b>{wo.prepared_by}</b><span>{when(wo.prepared_at)}</span></div>
        <div className="sign"><div>{wo.status === 'rejected' ? 'Rejected' : 'Approved'} by (field supervisor)</div><b>{wo.reviewed_by ?? '—'}</b><span>{when(wo.reviewed_at)}{wo.note ? ` · ${wo.note}` : ''}</span></div>
      </div>
      <div style={{ fontSize: 10, marginTop: 14, color: '#555' }}>
        Generated by WellTwin (SIH26120 prototype). Forecasts are model estimates; prototype runs on synthetic history calibrated to published Baghewala data.
      </div>
    </div>
  )
}

/** Plan → work order → four-eyes approval → print. */
export function WorkOrderFlow({ mission, onClose, auto }: { mission: Mission; onClose: () => void; auto: boolean }) {
  const [wo, setWo] = useState<WorkOrder | null>(null)
  const [prep, setPrep] = useState('')
  const [rev, setRev] = useState('')
  const [err, setErr] = useState('')
  const act = (p: Promise<WorkOrder>) => { setErr(''); p.then(setWo).catch((e) => setErr(e instanceof Error ? e.message : String(e))) }
  const submit = (name = prep) => act(api.woCreate(mission, name))
  const review = (approve: boolean, name = rev) => wo && act(api.woReview(wo.id, name, approve))

  useAfter(auto && !wo, 1200, () => { setPrep('Production Engineer'); submit('Production Engineer') })
  useAfter(auto && wo?.status === 'submitted', 2200, () => { setRev('Field Supervisor'); review(true, 'Field Supervisor') })
  useAfter(auto && wo?.status === 'approved', 4000, onClose)

  return (
    <div className="modal no-print-bg" onClick={onClose}>
      <div className="modal-body" onClick={(e) => e.stopPropagation()}>
        <div className="no-print" style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14, flexWrap: 'wrap' }}>
          <div className="label">Work order · four-eyes sign-off</div>
          {!wo && (
            <>
              <input className="text" placeholder="Prepared by (engineer name)" value={prep} onChange={(e) => setPrep(e.target.value)} />
              <button className="btn" style={{ padding: '8px 14px', fontSize: 12 }} disabled={prep.trim().length < 2} onClick={() => submit()}>SUBMIT FOR APPROVAL</button>
            </>
          )}
          {wo?.status === 'submitted' && (
            <>
              <input className="text" placeholder="Approver (supervisor name)" value={rev} onChange={(e) => setRev(e.target.value)} />
              <button className="btn" style={{ padding: '8px 14px', fontSize: 12 }} disabled={rev.trim().length < 2} onClick={() => review(true)}>APPROVE &amp; ISSUE</button>
              <button className="btn ghost" disabled={rev.trim().length < 2} onClick={() => review(false)}>REJECT</button>
            </>
          )}
          {wo && wo.status !== 'submitted' && <button className="btn" style={{ padding: '8px 14px', fontSize: 12 }} onClick={() => window.print()}>PRINT / SAVE PDF</button>}
          <button className="btn ghost" style={{ marginLeft: 'auto' }} onClick={onClose}>CLOSE</button>
          {err && <div className="mono red" style={{ width: '100%', fontSize: 12 }}>{err}</div>}
        </div>
        {wo ? <WorkOrderDoc wo={wo} /> : <div className="mono muted" style={{ padding: 40, textAlign: 'center' }}>Enter the preparing engineer's name to issue the recommended plan as a work order.</div>}
      </div>
    </div>
  )
}
